# Generated by Django 5.0 on 2024-01-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
