# Generated by Django 4.2 on 2023-04-27 08:51

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1275)),
                ('price', models.FloatField()),
                ('rate', models.FloatField(default=-1)),
                ('delivery_delay', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True, validators=[products.models.validate_date_past])),
                ('main_image', models.ImageField(upload_to=products.models.get_upload_path)),
                ('sale_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=1275)),
                ('join_date', models.DateTimeField(auto_now_add=True, validators=[products.models.validate_date_now])),
                ('rate', models.FloatField(default=-1)),
                ('logo', models.ImageField(upload_to=products.models.get_upload_path)),
                ('sale_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=products.models.get_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.seller'),
        ),
    ]
