# Generated by Django 5.0 on 2024-01-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('description', models.TextField(max_length=1999)),
                ('logo', models.ImageField(upload_to='')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(choices=[('FR', 'France'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('CH', 'Switzerland'), ('RU', 'Russia'), ('BE', 'Belgium'), ('PL', 'Poland'), ('IR', 'Iran')], max_length=99)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
