# Generated by Django 5.0 on 2024-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='associate',
            name='sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
