# Generated by Django 5.0 on 2024-01-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
                ('description', models.TextField(max_length=1999)),
                ('logo', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('kitchen', 'Kitchen'), ('electronics', 'Electronics'), ('clothing', 'Clothing')], max_length=99)),
                ('holding', models.CharField(choices=[('SF', 'San Francisco'), ('LA', 'Los Angeles'), ('CHI', 'Chicago'), ('NY', 'New York'), ('LON', 'London'), ('TOK', 'Tokyo'), ('BER', 'Berlin'), ('PEK', 'Beijing'), ('DEL', 'Delhi')], max_length=99)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associates.associate')),
            ],
        ),
    ]
