# Generated by Django 5.0 on 2024-01-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('SDD', 'Same day delivery'), ('FD', 'Fast delivery'), ('ND', 'Normal delivery')], max_length=99)),
                ('status', models.CharField(choices=[('SNT', 'Sent to reeceiver'), ('CNC', 'Canceled'), ('LST', 'Lost'), ('DMG', 'Damaged'), ('CRT', 'Created'), ('REF', 'Refunded'), ('FIN', 'Delivered')], max_length=99)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
            ],
        ),
    ]
