# Generated by Django 5.0 on 2024-01-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_is_active_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='hi', max_length=199),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='23', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('LST', 'Lost'), ('FIN', 'Delivered'), ('REF', 'Refunded'), ('SNT', 'Sent to reeceiver'), ('DMG', 'Damaged'), ('CNC', 'Canceled'), ('CRT', 'Created')], max_length=99),
        ),
    ]
