# Generated by Django 5.0 on 2024-01-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_is_active_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CNC', 'Canceled'), ('REF', 'Refunded'), ('LST', 'Lost'), ('FIN', 'Delivered'), ('SNT', 'Sent to reeceiver'), ('DMG', 'Damaged'), ('CRT', 'Created')], default='Created', max_length=99),
        ),
    ]
